### ISSUE TITLE
Compiling Error Message

### ISSUE THREAD

**Issue by TheKrueg1998** [dmgcoin/dmgcoin#1]
Any idea how to fix this problem? I come across this issue every single time I try to compile the files... Thank you!

![image](https://github.com/dmgcoin/dmgcoin/assets/80941977/987525a3-c486-4367-99d0-a1017215f516)

**Comment by dmgcoin** [comment]
Currently not compatible with 32 bit systems . Try running on 64 bit

**Comment by dmgcoin** [comment]
Then it must be go installation issue . Ensure that the Go environment is set up correctly for 64-bit compilation. You can check this by running `go env` in the command line and looking for the GOARCH variable. It should be like amd64 or arm64 for 64-bit compilations.

**Comment by apurvns** [comment]
> Okay we aren't getting that error message anymore. For what ever reason golang finally installed 64 bit instead of 32 bit this time. So I have ran those commands but I still dont see any compiled files under C:\Program Files\Go\bin so what final step am I missing?

From the root dmgcoin folder run 'go install . ./cmd/...'
