### ISSUE TITLE
error starting dmgcoin.exe

### ISSUE THREAD

**Issue by R0glin** [dmgcoin/dmgcoin#2]
 ./dmgcoin.exe --utxoindex --appdir G:\Users\Roglin\AppData\Local\Dmgcoin
2024-04-17 22:43:54.454 [INF] DMGC: Version 0.12.15
2024-04-17 22:43:54.463 [INF] DMGC: Loading database from 'G:\Users\Roglin\AppData\Local\Dmgcoin\dmgcoin-mainnet\datadir2'
2024-04-17 22:43:54.547 [ERR] DMGC: Unable to start dmgcoin: ErrBadCoinbasePayloadLen
coinbase payload doesn't have enough bytes to contain a script public key of 34 bytes
github.com/dmgcoin/dmgcoin/domain/consensus/processes/coinbasemanager.(*coinbaseManager).ExtractCoinbaseDataBlueScoreAndSubsidy
        E:/msys64/home/Roglin/dmgcoin/domain/consensus/processes/coinbasemanager/payload.go:86
github.com/dmgcoin/dmgcoin/domain/consensus/processes/blockvalidator.(*blockValidator).checkCoinbaseBlueScore
        E:/msys64/home/Roglin/dmgcoin/domain/consensus/processes/blockvalidator/block_body_in_isolation.go:95
github.com/dmgcoin/dmgcoin/domain/consensus/processes/blockvalidator.(*blockValidator).ValidateBodyInIsolation
        E:/msys64/home/Roglin/dmgcoin/domain/consensus/processes/blockvalidator/block_body_in_isolation.go:51
github.com/dmgcoin/dmgcoin/domain/consensus/processes/blockprocessor.(*blockProcessor).validatePostProofOfWork
        E:/msys64/home/Roglin/dmgcoin/domain/consensus/processes/blockprocessor/validate_and_insert_block.go:327
github.com/dmgcoin/dmgcoin/domain/consensus/processes/blockprocessor.(*blockProcessor).validateBlock
        E:/msys64/home/Roglin/dmgcoin/domain/consensus/processes/blockprocessor/validate_block.go:56
github.com/dmgcoin/dmgcoin/domain/consensus/processes/blockprocessor.(*blockProcessor).validateAndInsertBlock
        E:/msys64/home/Roglin/dmgcoin/domain/consensus/processes/blockprocessor/validate_and_insert_block.go:83
github.com/dmgcoin/dmgcoin/domain/consensus/processes/blockprocessor.(*blockProcessor).validateAndInsertBlockWithTrustedData
        E:/msys64/home/Roglin/dmgcoin/domain/consensus/processes/blockprocessor/validate_and_insert_block_with_trusted_data.go:34
github.com/dmgcoin/dmgcoin/domain/consensus/processes/blockprocessor.(*blockProcessor).ValidateAndInsertBlockWithTrustedData
        E:/msys64/home/Roglin/dmgcoin/domain/consensus/processes/blockprocessor/blockprocessor.go:171
github.com/dmgcoin/dmgcoin/domain/consensus.(*consensus).Init
        E:/msys64/home/Roglin/dmgcoin/domain/consensus/consensus.go:146
github.com/dmgcoin/dmgcoin/domain/consensus.(*factory).NewConsensus
        E:/msys64/home/Roglin/dmgcoin/domain/consensus/factory.go:529
github.com/dmgcoin/dmgcoin/domain.New
        E:/msys64/home/Roglin/dmgcoin/domain/domain.go:202
github.com/dmgcoin/dmgcoin/app.NewComponentManager
        E:/msys64/home/Roglin/dmgcoin/app/component_manager.go:91
github.com/dmgcoin/dmgcoin/app.(*dmgcoinApp).main
        E:/msys64/home/Roglin/dmgcoin/app/app.go:126
github.com/dmgcoin/dmgcoin/app.StartApp
        E:/msys64/home/Roglin/dmgcoin/app/app.go:73
main.main
        E:/msys64/home/Roglin/dmgcoin/main.go:15
runtime.main
        E:/msys64/mingw64/lib/go/src/runtime/proc.go:267
runtime.goexit
        E:/msys64/mingw64/lib/go/src/runtime/asm_amd64.s:1650
2024-04-17 22:43:54.547 [INF] DMGC: Gracefully shutting down the database...
2024-04-17 22:43:54.563 [INF] DMGC: Shutdown complete

**Comment by dmgcoin** [comment]
Will be announced on twitter : https://twitter.com/dmgcmeme
