### ISSUE TITLE
Algo & Tokenomics

### ISSUE THREAD

**Issue by TheKrueg1998** [dmgcoin/dmgcoin#6]
Have you decided on the algo yet? I read that there will be a total supply of 21 million coins, but have you decided on what block reward will be?

**Comment by dmgcoin** [comment]
Dark Magician Girl Coin ($DMGC)
Algorithm  - KHeavyHash
Mineable - PoW based meme coin
Mainnet launch date - April 22, 2024, at 9 PM ET
The Pre-Deflationary Phase - first 24-hour window where miners can generate around 200K DMGC tokens, nearly 0.90% of the total supply, after which block reward will be reduced to 0.0176 DMG per block.
