### ISSUE TITLE
Final Question - Mining

### ISSUE THREAD

**Issue by TheKrueg1998** [dmgcoin/dmgcoin#7]
Will there be a stratum bridge to solo mine the coin when it launches? If no, will it be on any pools?

**Comment by dmgcoin** [comment]
No stratum bridge till pre deflationary period, after 24 hours stratum bridge will be available . 
Pool listing will also done after few weeks so let solo miners get benefit from the launch.

**Comment by Kali123411** [comment]
scam coin
